http:
  routers:
    traefik-dashboard:
      rule: "PathPrefix(`/`)"
      service: api@internal
      entryPoints:
        - dashboard
      middlewares:
        - dashboard-auth

  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - "admin:$apr1$hh7QEauV$zrQQRwL8XQh531aT5GJV9." # admin:password

    correlation:
      plugin:
        correlation:
          headerName: "X-Request-ID"